### ISSUE TITLE
LOGIN FAILED

### ISSUE THREAD

**Issue by Deakula** [ErinvanderVeen/Reddit-RSS-Bot#1]
Whenever I run the bot and put in my bot username and password, it always comes back and says "Login Failed". I've tried multiple times and I know the username and password is correct.

**Comment by ErinvanderVeen** [comment]
I haven't looked at this project since the week I created it. I'm sure many things have changed at reddit. I do not intend to update the program. I'm sorry for the inconvenience. I shall update the readme to reflect that this project is discontinued.
